[2025-01-02T00:03:22.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T00:03:22.030+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.create_tables manual__2025-01-02T00:03:19.734231+00:00 [queued]>
[2025-01-02T00:03:22.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.create_tables manual__2025-01-02T00:03:19.734231+00:00 [queued]>
[2025-01-02T00:03:22.044+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-02T00:03:22.063+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_tables> on 2025-01-02 00:03:19.734231+00:00
[2025-01-02T00:03:22.073+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T00:03:22.075+0000] {standard_task_runner.py:72} INFO - Started process 476 to run task
[2025-01-02T00:03:22.076+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'create_tables', 'manual__2025-01-02T00:03:19.734231+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmp_wmo_qgg']
[2025-01-02T00:03:22.077+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask create_tables
[2025-01-02T00:03:22.095+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-02T00:03:22.146+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.create_tables manual__2025-01-02T00:03:19.734231+00:00 [running]> on host a26fd2b06b06
[2025-01-02T00:03:22.264+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:03:19.734231+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T00:03:19.734231+00:00'
[2025-01-02T00:03:22.264+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T00:03:22.283+0000] {utils.py:59} INFO - News sentiment analysis database connection established successfully.
[2025-01-02T00:03:22.347+0000] {create_table_dag.py:25} INFO - Tables created successfully
[2025-01-02T00:03:22.348+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T00:03:22.362+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T00:03:22.362+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=create_tables, run_id=manual__2025-01-02T00:03:19.734231+00:00, execution_date=20250102T000319, start_date=20250102T000322, end_date=20250102T000322
[2025-01-02T00:03:22.413+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T00:03:22.436+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T00:03:22.439+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
